---
- name: TERMINAOR!
  hosts: all
 
  tasks:

  - name: Remove image
    docker_image:
      force_absent: yes
      state: absent
      name: 192.168.218.130:80/pepapp/pepappimage
      tag: latest
