---
- name: TERMINAOR!
  hosts: all
 
  tasks:

  - name: Remove image
    docker_image:
      state: absent
      force_absent: yes
      name: 192.168.218.130:80/portalapp/portalappimage
      tag: latest
